Repository depromeet/omo-frontend, pull requests merged in 2021-11, with the labels that each got.

#34 feature/OMO-55-71/매장상세페이지 리뉴얼
  next.config.js
  package-lock.json
  package.json
  src/components/Header/HeaderInput.tsx
  src/components/StoreDescription/StoreDescription.tsx
  src/components/StoreDescription/styles.ts
  src/components/StoreDisplay/StoreDisplayList.tsx
  src/components/StoreDisplay/styles.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/pages/search/[id].tsx
  src/pages/search/index.tsx
  src/styles/globalStyles.ts
  src/temp/SearchListDummy.ts
  yarn.lock
Labels: ⚒️ refactor

#35 feature/OMO-70/인증페이지 작성
  public/images/omo_logo.png
  src/components/Certification/LocationChecker.tsx
  src/components/Certification/ReceiptChecker.tsx
  src/components/Certification/index.ts
  src/components/Certification/styles.tsx
  src/components/Shared/Modal/CertificationModal.tsx
  src/components/Shared/Modal/index.tsx
  src/components/Shared/Modal/styles.ts
  src/pages/certification/guide.tsx
  src/pages/certification/index.tsx
  src/pages/search/[id].tsx
  src/utils/convertFileToBlobUrl.ts
Labels: ✨ new feature, ⚒️ refactor

#38 Feature/OMO-99/요청 함수 구현
  src/pages/home.tsx
  src/request/index.ts
  src/utils/getObjectFormQuery.ts
Labels: ✨ new feature

#39 feature/OMO-70/인증페이지 바텀 액션 시트 레이아웃 작성
  src/components/Certification/LocationChecker.tsx
  src/components/Certification/SearchBottomActionSheet.tsx
  src/components/Certification/index.ts
  src/components/Certification/styles.tsx
  src/lib/.gitkeep
  src/lib/PreventLinkAction.tsx
  src/pages/certification/index.tsx
  src/pages/search/index.tsx
Labels: ✨ new feature, ⚒️ refactor

#40 Feature/OMO-104/user/~ API 연동
  src/@types/shared.ts
  src/components/Header/MyPageHeader.tsx
  src/components/MyProfile/MyProfile.tsx
  src/components/NicknameInput/NicknameInput.tsx
  src/components/ProfileImage/ProfileImage.tsx
  src/components/SearchRecord/SearchRecord.tsx
  src/constants/error.ts
  src/pages/home.tsx
  src/pages/login/index.tsx
  src/pages/login/nickname.tsx
  src/pages/login/profile.tsx
  src/pages/mypage/changeNickName.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/signout.tsx
  src/pages/ranking/index.tsx
  src/recoil/signupFormState.ts
  src/recoil/userState.ts
  src/request/index.ts
  src/utils/handleError.ts
  src/utils/modal.ts
Labels: ✨ new feature

#43 Feature/OMO-107/프로필 사진 변경 API 연동
  src/components/Header/MyPageHeader.tsx
  src/components/MyProfile/MyProfile.tsx
  src/components/MyProfile/styles.ts
  src/constants/error.ts
  src/pages/home.tsx
  src/pages/login/nickname.tsx
  src/pages/mypage/changeNickName.tsx
  src/pages/mypage/changePhoto.tsx
  src/pages/mypage/index.tsx
  src/recoil/signupFormState.ts
  src/recoil/userState.ts
  src/request/index.ts
  src/utils/convertURLtoFile.ts
  src/utils/getObjectFormQuery.ts
  src/utils/setRefreshTokenOnCookie.ts
Labels: ✨ new feature

#44 Feature/OMO-108/오마카세 검색 및 인증 관련 리코일 상태관리 및 API 연동
  package-lock.json
  package.json
  public/images/default-image.jpg
  public/images/reviewed_certification.png
  public/images/reviewing_certification.png
  src/api/hello.ts
  src/assets/favorite_border.svg
  src/components/Certification/ReceiptChecker.tsx
  src/components/Certification/SearchBottomActionSheet.tsx
  src/components/SearchResults/SearchResults.tsx
  src/components/SearchResults/index.ts
  src/components/SearchResults/styles.ts
  src/components/Shared/Loading/LoadingSpinner.tsx
  src/components/Shared/Loading/PageLoading.tsx
  src/components/Shared/Loading/index.ts
  src/components/Shared/Loading/styles.ts
  src/components/Shared/Modal/GradeDescriptionModal.tsx
  src/components/StoreDescription/StoreDescription.tsx
  src/components/StoreDescription/styles.ts
  src/hooks/useIntersection.tsx
  src/pages/_app.tsx
  src/pages/api/omakase/[id].js
  src/pages/api/omakases.js
  src/pages/api/recommendation/[id].js
  src/pages/api/stamp.js
  src/pages/certification/guide.tsx
  src/pages/certification/index.tsx
  src/pages/search/[id].tsx
  src/pages/search/index.tsx
  src/pages/search/searching.tsx
  src/recoil/certificationState.ts
  src/recoil/omakaseState.ts
  src/request/index.ts
  src/styles/colors.ts
  yarn.lock
Labels: 🎸 chore, ✨ new feature, ⚒️ refactor

#45 Feature/omo 100
  src/components/Shared/RankingCard/RankingCard.tsx
  src/pages/home.tsx
  src/pages/mypage/settings.tsx
  src/pages/ranking/index.tsx
  src/recoil/rankerState.ts
  src/request/index.ts
Labels: ✨ new feature

#48 fix: 전역상태 keyword 버그 수정
  src/pages/search/index.tsx
  src/pages/search/searching.tsx
Labels: 🐛 bug
